import { Footer, Navbar, ThemeProviders } from '@/components';
import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'MiraTOP Page',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html suppressHydrationWarning>
			<body>
				<ThemeProviders>
					<Navbar />
					{children}
					<Footer />
				</ThemeProviders>
			</body>
		</html>
	);
}
