import { ClientProvider, Footer, Navbar, ThemeProviders } from '@/components';
import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'MiraTOP',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html suppressHydrationWarning lang='es'>
			<body>
				<ThemeProviders>
					<ClientProvider>
						<Navbar />
						{children}
						<Footer />
					</ClientProvider>
				</ThemeProviders>
			</body>
		</html>
	);
}
